"""normalize_academic_entities

Revision ID: 586aa055b825
Revises: 20260518_03
Create Date: 2026-05-20 11:20:32.378270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586aa055b825'
down_revision: Union[str, None] = '20260518_03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    
    try:
        op.drop_index('ix_test_attempts_student_test_completed', table_name='test_attempts')
    except Exception:
        pass

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('program_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admission_year', sa.Integer(), nullable=True))
        
        try:
            batch_op.drop_index('ix_users_telegram_link_code')
        except Exception:
            pass
            
        batch_op.create_unique_constraint('uq_users_telegram_link_code', ['telegram_link_code'])
        batch_op.create_foreign_key('fk_users_faculties', 'faculties', ['faculty_id'], ['id'])
        batch_op.create_foreign_key('fk_users_departments', 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key('fk_users_programs', 'programs', ['program_id'], ['id'])
        
        batch_op.drop_column('faculty')
        batch_op.drop_column('course')
        batch_op.drop_column('department')
        batch_op.drop_column('program_code')


def downgrade() -> None:
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_code', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('department', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('course', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('faculty', sa.VARCHAR(length=120), nullable=True))
        
        batch_op.drop_constraint('fk_users_programs', type_='foreignkey')
        batch_op.drop_constraint('fk_users_departments', type_='foreignkey')
        batch_op.drop_constraint('fk_users_faculties', type_='foreignkey')
        batch_op.drop_constraint('uq_users_telegram_link_code', type_='unique')
        
        batch_op.create_index('ix_users_telegram_link_code', ['telegram_link_code'], unique=False)
        
        batch_op.drop_column('admission_year')
        batch_op.drop_column('program_id')
        batch_op.drop_column('department_id')
        batch_op.drop_column('faculty_id')
        
    try:
        op.create_index('ix_test_attempts_student_test_completed', 'test_attempts', ['student_id', 'test_id', 'status'], unique=False)
    except Exception:
        pass
        
    op.drop_table('programs')
    op.drop_table('departments')
    op.drop_table('faculties')
    # ### end Alembic commands ###
